// Mock CRM data for demonstration

export const mockContacts = [
    {
        id: '1',
        firstName: 'Sarah',
        lastName: 'Johnson',
        email: 'sarah.johnson@techcorp.com',
        phone: '+1 (555) 123-4567',
        company: 'TechCorp Industries',
        jobTitle: 'VP of Engineering',
        status: 'active',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
        createdAt: new Date('2024-01-15'),
    },
    {
        id: '2',
        firstName: 'Michael',
        lastName: 'Chen',
        email: 'michael.chen@innovate.io',
        phone: '+1 (555) 234-5678',
        company: 'Innovate Solutions',
        jobTitle: 'CTO',
        status: 'active',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
        createdAt: new Date('2024-02-20'),
    },
    {
        id: '3',
        firstName: 'Emily',
        lastName: 'Rodriguez',
        email: 'emily.r@globaltech.com',
        phone: '+1 (555) 345-6789',
        company: 'GlobalTech Systems',
        jobTitle: 'Product Manager',
        status: 'active',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
        createdAt: new Date('2024-03-10'),
    },
    {
        id: '4',
        firstName: 'David',
        lastName: 'Kim',
        email: 'david.kim@startup.co',
        phone: '+1 (555) 456-7890',
        company: 'Startup Hub',
        jobTitle: 'CEO',
        status: 'active',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
        createdAt: new Date('2024-04-05'),
    },
    {
        id: '5',
        firstName: 'Lisa',
        lastName: 'Anderson',
        email: 'lisa.anderson@enterprise.com',
        phone: '+1 (555) 567-8901',
        company: 'Enterprise Corp',
        jobTitle: 'Director of Sales',
        status: 'active',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
        createdAt: new Date('2024-05-12'),
    },
    {
        id: '6',
        firstName: 'James',
        lastName: 'Wilson',
        email: 'james.w@cloudservices.io',
        phone: '+1 (555) 678-9012',
        company: 'Cloud Services Ltd',
        jobTitle: 'Solutions Architect',
        status: 'active',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
        createdAt: new Date('2024-06-18'),
    },
];

export const mockDeals = [
    {
        id: '1',
        title: 'Enterprise Integration',
        value: 250000,
        stage: 'proposal',
        probability: 75,
        expectedCloseDate: new Date('2024-12-31'),
        contactId: '1',
        contactName: 'Sarah Johnson',
        companyName: 'TechCorp Industries',
        owner: 'You',
        createdAt: new Date('2024-11-01'),
    },
    {
        id: '2',
        title: 'Cloud Migration Project',
        value: 180000,
        stage: 'negotiation',
        probability: 60,
        expectedCloseDate: new Date('2025-01-15'),
        contactId: '2',
        contactName: 'Michael Chen',
        companyName: 'Innovate Solutions',
        owner: 'You',
        createdAt: new Date('2024-10-15'),
    },
    {
        id: '3',
        title: 'API Platform Upgrade',
        value: 95000,
        stage: 'qualified',
        probability: 40,
        expectedCloseDate: new Date('2025-02-01'),
        contactId: '3',
        contactName: 'Emily Rodriguez',
        companyName: 'GlobalTech Systems',
        owner: 'Sales Team',
        createdAt: new Date('2024-11-20'),
    },
    {
        id: '4',
        title: 'Custom Development',
        value: 450000,
        stage: 'lead',
        probability: 25,
        expectedCloseDate: new Date('2025-03-15'),
        contactId: '4',
        contactName: 'David Kim',
        companyName: 'Startup Hub',
        owner: 'You',
        createdAt: new Date('2024-12-01'),
    },
    {
        id: '5',
        title: 'Annual Support Contract',
        value: 120000,
        stage: 'closed-won',
        probability: 100,
        expectedCloseDate: new Date('2024-11-30'),
        contactId: '5',
        contactName: 'Lisa Anderson',
        companyName: 'Enterprise Corp',
        owner: 'You',
        createdAt: new Date('2024-09-10'),
    },
];

export const mockTasks = [
    {
        id: '1',
        title: 'Follow-up call with Sarah Johnson',
        description: 'Discuss proposal details and timeline',
        type: 'call',
        status: 'pending',
        priority: 'high',
        dueDate: new Date('2024-12-15'),
        assignedTo: 'You',
        relatedTo: 'deal-1',
        createdAt: new Date('2024-12-10'),
    },
    {
        id: '2',
        title: 'Send proposal to Michael Chen',
        description: 'Cloud migration proposal with pricing',
        type: 'email',
        status: 'pending',
        priority: 'high',
        dueDate: new Date('2024-12-16'),
        assignedTo: 'You',
        relatedTo: 'deal-2',
        createdAt: new Date('2024-12-11'),
    },
    {
        id: '3',
        title: 'Schedule demo for GlobalTech',
        description: 'Product demonstration for Emily Rodriguez',
        type: 'meeting',
        status: 'pending',
        priority: 'medium',
        dueDate: new Date('2024-12-18'),
        assignedTo: 'Sales Team',
        relatedTo: 'deal-3',
        createdAt: new Date('2024-12-12'),
    },
    {
        id: '4',
        title: 'Contract review with Legal',
        description: 'Review Enterprise Corp contract terms',
        type: 'meeting',
        status: 'completed',
        priority: 'high',
        dueDate: new Date('2024-11-28'),
        assignedTo: 'You',
        relatedTo: 'deal-5',
        createdAt: new Date('2024-11-25'),
    },
];

export const mockCompanies = [
    {
        id: '1',
        name: 'TechCorp Industries',
        industry: 'Technology',
        size: '500-1000',
        revenue: 50000000,
        website: 'https://techcorp.example.com',
        address: '123 Tech Street, San Francisco, CA 94105',
        createdAt: new Date('2024-01-15'),
    },
    {
        id: '2',
        name: 'Innovate Solutions',
        industry: 'Software',
        size: '100-500',
        revenue: 15000000,
        website: 'https://innovate.example.com',
        address: '456 Innovation Ave, Austin, TX 78701',
        createdAt: new Date('2024-02-20'),
    },
    {
        id: '3',
        name: 'GlobalTech Systems',
        industry: 'Enterprise Software',
        size: '1000-5000',
        revenue: 100000000,
        website: 'https://globaltech.example.com',
        address: '789 Global Plaza, New York, NY 10001',
        createdAt: new Date('2024-03-10'),
    },
];
